module.exports = [ { method: 'GET',
    url: '/backend/outbound/newOutboundPage',
    sync: false,
    filePath: 'get/backend/outbound/newOutboundPage/data',
    id: 18035 },
  { method: 'POST',
    url: '/storage/template/submit',
    sync: false,
    filePath: 'post/storage/template/submit/data',
    id: 16975 },
  { method: 'POST',
    url: '/storage/template/remove',
    sync: false,
    filePath: 'post/storage/template/remove/data',
    id: 16969 },
  { method: 'GET',
    url: '/storage/template/init',
    sync: true,
    filePath: 'page\\4pl\\expenseTemplate\\list',
    id: 11213 },
  { method: 'GET',
    url: '/storage/template/edit',
    sync: true,
    filePath: 'page\\4pl\\expenseTemplate\\add',
    id: 11214 },
  { method: 'GET',
    url: '/storage/template/copy',
    sync: true,
    filePath: 'page\\4pl\\expenseTemplate\\add',
    id: 11214 },
  { method: 'POST',
    url: '/storage/template/copy',
    sync: false,
    filePath: 'post/storage/template/copy/data',
    id: 16982 },
  { method: 'GET',
    url: '/storage/template/add',
    sync: true,
    filePath: 'page\\4pl\\expenseTemplate\\add',
    id: 11214 },
  { method: 'GET',
    url: '/storage/expenseMng',
    sync: true,
    filePath: 'page\\4pl\\expenseMng\\expenseMng',
    id: 11211 },
  { method: 'POST',
    url: '/storage/additionalFee/update',
    sync: false,
    filePath: 'post/storage/additionalFee/update/data',
    id: 17242 },
  { method: 'POST',
    url: '/storage/additionalFee/remove',
    sync: false,
    filePath: 'post/storage/additionalFee/remove/data',
    id: 17240 },
  { method: 'GET',
    url: '/storage/additionalFee/list',
    sync: false,
    filePath: 'get/storage/additionalFee/list/data',
    id: 17241 },
  { method: 'GET',
    url: '/storage/additionalFee/init',
    sync: true,
    filePath: 'page\\4pl\\additionalFee\\list',
    id: 11316 },
  { method: 'POST',
    url: '/storage/additionalFee/add',
    sync: false,
    filePath: 'post/storage/additionalFee/add/data',
    id: 17239 },
  { method: 'POST',
    url: '/salesreport/skuprofits/exportDetail',
    sync: false,
    filePath: 'post/salesreport/skuprofits/exportDetail/data',
    id: 16686 },
  { method: 'GET',
    url: '/salesreport/multiOrderProfits/stat',
    sync: false,
    filePath: 'get/salesreport/multiOrderProfits/stat/data',
    id: 16687 },
  { method: 'GET',
    url: '/salesreport/multiOrderProfits/index',
    sync: false,
    filePath: 'get/salesreport/multiOrderProfits/index/data',
    id: 16659 },
  { method: 'POST',
    url: '/salesreport/multiOrderProfits/exportReport',
    sync: false,
    filePath: 'post/salesreport/multiOrderProfits/exportReport/data',
    id: 16688 },
  { method: 'POST',
    url: '/salesreport/multiOrderProfits/exportDetail',
    sync: false,
    filePath: 'post/salesreport/multiOrderProfits/exportDetail/data',
    id: 16689 },
  { method: 'GET',
    url: '/salesReport/multiSkuProfits/list',
    sync: true,
    filePath: 'page\\pricemodel\\multiSkupPofits',
    id: 11177 },
  { method: 'GET',
    url: '/salesReport/multiSkuProfits/index',
    sync: false,
    filePath: 'get/salesReport/multiSkuProfits/index/data',
    id: 16679 },
  { method: 'POST',
    url: '/salesReport/multiSkuProfits/exportReport',
    sync: false,
    filePath: 'post/salesReport/multiSkuProfits/exportReport/data',
    id: 16685 },
  { method: 'GET',
    url: '/salesReport/multiOrderProfits/list',
    sync: true,
    filePath: 'page\\pricemodel\\multiOrderProfits',
    id: 11171 },
  { method: 'POST',
    url: '/logis/warnSubscriber/remove',
    sync: false,
    filePath: 'post/logis/warnSubscriber/remove/data',
    id: 17258 },
  { method: 'POST',
    url: '/logis/warnSubscriber/list',
    sync: false,
    filePath: 'post/logis/warnSubscriber/list/data',
    id: 17259 },
  { method: 'GET',
    url: '/logis/warnSubscriber/init',
    sync: true,
    filePath: 'page\\4pl\\logis\\warnSubscriber',
    id: 11320 },
  { method: 'POST',
    url: '/logis/warnSubscriber/add',
    sync: false,
    filePath: 'post/logis/warnSubscriber/add/data',
    id: 17257 },
  { method: 'POST',
    url: '/flow/shop/getShopSearchList',
    sync: false,
    filePath: 'post/flow/shop/getShopSearchList/data',
    id: 17635 },
  { method: 'POST',
    url: '/districtDelivery/getCategoryList',
    sync: false,
    filePath: 'post/districtDelivery/getCategoryList/data',
    id: 17054 },
  { method: 'POST',
    url: '/categoryAdviser/categoryOverview/transformOverview',
    sync: false,
    filePath: 'post/categoryAdviser/categoryOverview/transformOverview/data',
    id: 17939 },
  { method: 'GET',
    url: '/backend/upload/index',
    sync: true,
    filePath: 'page\\system\\uploader\\index',
    id: 11095 },
  { method: 'POST',
    url: '/backend/upload',
    sync: false,
    filePath: 'post/backend/upload/data',
    id: 16000 },
  { method: 'POST',
    url: '/backend/test/list',
    sync: false,
    filePath: 'post/backend/test/list/data',
    id: 14690 },
  { method: 'GET',
    url: '/backend/test/demo1',
    sync: true,
    filePath: 'page\\test\\index',
    id: 10845 },
  { method: 'GET',
    url: '/backend/test/demo',
    sync: true,
    filePath: 'page\\test\\demo',
    id: 11912 },
  { method: 'POST',
    url: '/backend/system/notify/subscribe',
    sync: false,
    filePath: 'post/backend/system/notify/subscribe/data',
    id: 18024 },
  { method: 'POST',
    url: '/backend/system/notify/setSingleRead',
    sync: false,
    filePath: 'post/backend/system/notify/setSingleRead/data',
    id: 18181 },
  { method: 'POST',
    url: '/backend/system/notify/setAllRead',
    sync: false,
    filePath: 'post/backend/system/notify/setAllRead/data',
    id: 18023 },
  { method: 'GET',
    url: '/backend/system/notify/messages',
    sync: true,
    filePath: 'page\\system\\notify\\list',
    id: 11514 },
  { method: 'GET',
    url: '/backend/system/notify/list',
    sync: false,
    filePath: 'get/backend/system/notify/list/data',
    id: 18022 },
  { method: 'POST',
    url: '/backend/system/notify/broadcastMsg',
    sync: false,
    filePath: 'post/backend/system/notify/broadcastMsg/data',
    id: 18475 },
  { method: 'POST',
    url: '/backend/supplychain/updateGoodSupplierMainSub',
    sync: false,
    filePath: 'post/backend/supplychain/updateGoodSupplierMainSub/data',
    id: 16253 },
  { method: 'GET',
    url: '/backend/supplychain/getSupplierDeltaAmount',
    sync: false,
    filePath: 'get/backend/supplychain/getSupplierDeltaAmount/data',
    id: 17069 },
  { method: 'POST',
    url: '/backend/supplierMainSubSet/updateBrandSupplier',
    sync: false,
    filePath: 'post/backend/supplierMainSubSet/updateBrandSupplier/data',
    id: 16221 },
  { method: 'GET',
    url: '/backend/supplierMainSubSet/getGoodsSupplierList',
    sync: true,
    filePath: 'page\\supplychain\\supplier\\goodSupplierMainSubSet',
    id: 11116 },
  { method: 'POST',
    url: '/backend/supplierMainSubSet/getGoodsSupplierList',
    sync: false,
    filePath: 'post/backend/supplierMainSubSet/getGoodsSupplierList/data',
    id: 16241 },
  { method: 'POST',
    url: '/backend/supplierMainSubSet/getCategoryList',
    sync: false,
    filePath: 'post/backend/supplierMainSubSet/getCategoryList/data',
    id: 16223 },
  { method: 'GET',
    url: '/backend/supplierMainSubSet/getCategoryList',
    sync: false,
    filePath: 'get/backend/supplierMainSubSet/getCategoryList/data',
    id: 16353 },
  { method: 'GET',
    url: '/backend/supplierMainSubSet/getBrandSupplierList',
    sync: false,
    filePath: 'get/backend/supplierMainSubSet/getBrandSupplierList/data',
    id: 16220 },
  { method: 'POST',
    url: '/backend/supplierMainSubSet/getBrandList',
    sync: false,
    filePath: 'post/backend/supplierMainSubSet/getBrandList/data',
    id: 16361 },
  { method: 'POST',
    url: '/backend/supplierMainSubSet/deleteBrandSupplier',
    sync: false,
    filePath: 'post/backend/supplierMainSubSet/deleteBrandSupplier/data',
    id: 16222 },
  { method: 'POST',
    url: '/backend/supplierMainSubSet/addBrandSupplier',
    sync: false,
    filePath: 'post/backend/supplierMainSubSet/addBrandSupplier/data',
    id: 16227 },
  { method: 'GET',
    url: '/backend/storage/warehouseConf',
    sync: true,
    filePath: 'page\\4pl\\warehouseConfig',
    id: 10815 },
  { method: 'POST',
    url: '/backend/storage/updateWarehouse',
    sync: false,
    filePath: 'post/backend/storage/updateWarehouse/data',
    id: 14579 },
  { method: 'POST',
    url: '/backend/storage/updateCustomesAgency',
    sync: false,
    filePath: 'post/backend/storage/updateCustomesAgency/data',
    id: 14597 },
  { method: 'POST',
    url: '/backend/storage/updateAddMark',
    sync: false,
    filePath: 'post/backend/storage/updateAddMark/data',
    id: 16963 },
  { method: 'GET',
    url: '/backend/storage/template/list',
    sync: false,
    filePath: 'get/backend/storage/template/list/data',
    id: 16961 },
  { method: 'POST',
    url: '/backend/storage/recompute',
    sync: false,
    filePath: 'post/backend/storage/recompute/data',
    id: 16964 },
  { method: 'GET',
    url: '/backend/storage/queryLocation',
    sync: false,
    filePath: 'get/backend/storage/queryLocation/data',
    id: 14573 },
  { method: 'POST',
    url: '/backend/storage/packageMaterial/update',
    sync: false,
    filePath: 'post/backend/storage/packageMaterial/update/data',
    id: 16973 },
  { method: 'POST',
    url: '/backend/storage/packageMaterial/remove',
    sync: false,
    filePath: 'post/backend/storage/packageMaterial/remove/data',
    id: 16972 },
  { method: 'GET',
    url: '/backend/storage/packageMaterial/manage',
    sync: true,
    filePath: 'page\\4pl\\packageMaterial\\manage',
    id: 11212 },
  { method: 'GET',
    url: '/backend/storage/packageMaterial/list',
    sync: false,
    filePath: 'get/backend/storage/packageMaterial/list/data',
    id: 16966 },
  { method: 'POST',
    url: '/backend/storage/packageMaterial/import',
    sync: false,
    filePath: 'post/backend/storage/packageMaterial/import/data',
    id: 16968 },
  { method: 'POST',
    url: '/backend/storage/modifyStorageFeeBid',
    sync: false,
    filePath: 'post/backend/storage/modifyStorageFeeBid/data',
    id: 16971 },
  { method: 'GET',
    url: '/backend/storage/list',
    sync: false,
    filePath: 'get/backend/storage/list/data',
    id: 14572 },
  { method: 'GET',
    url: '/backend/storage/getWarehouseRelateInfo',
    sync: false,
    filePath: 'get/backend/storage/getWarehouseRelateInfo/data',
    id: 14581 },
  { method: 'GET',
    url: '/backend/storage/getStorageFeeBid',
    sync: false,
    filePath: 'get/backend/storage/getStorageFeeBid/data',
    id: 16983 },
  { method: 'POST',
    url: '/backend/storage/deleteWarehouse',
    sync: false,
    filePath: 'post/backend/storage/deleteWarehouse/data',
    id: 14578 },
  { method: 'POST',
    url: '/backend/storage/deleteCustomesagency',
    sync: false,
    filePath: 'post/backend/storage/deleteCustomesagency/data',
    id: 14774 },
  { method: 'POST',
    url: '/backend/storage/delStorageFeeBid',
    sync: false,
    filePath: 'post/backend/storage/delStorageFeeBid/data',
    id: 16990 },
  { method: 'GET',
    url: '/backend/storage/customsAgencyConf',
    sync: true,
    filePath: 'page\\4pl\\customesBroker',
    id: 10824 },
  { method: 'GET',
    url: '/backend/storage/customesAgencylist',
    sync: false,
    filePath: 'get/backend/storage/customesAgencylist/data',
    id: 14593 },
  { method: 'POST',
    url: '/backend/storage/addWarehouse',
    sync: false,
    filePath: 'post/backend/storage/addWarehouse/data',
    id: 14577 },
  { method: 'POST',
    url: '/backend/storage/addStorageFeeBid',
    sync: false,
    filePath: 'post/backend/storage/addStorageFeeBid/data',
    id: 16962 },
  { method: 'POST',
    url: '/backend/storage/addCustomesAgency',
    sync: false,
    filePath: 'post/backend/storage/addCustomesAgency/data',
    id: 14582 },
  { method: 'POST',
    url: '/backend/specialAuditOrder/search',
    sync: false,
    filePath: 'post/backend/specialAuditOrder/search/data',
    id: 18129 },
  { method: 'GET',
    url: '/backend/specialAuditOrder/listPage',
    sync: true,
    filePath: 'page\\capitalpool\\specialauditorderlist',
    id: 11536 },
  { method: 'POST',
    url: '/backend/specialAuditOrder/exportlist',
    sync: false,
    filePath: 'post/backend/specialAuditOrder/exportlist/data',
    id: 18131 },
  { method: 'POST',
    url: '/backend/outboundTask/search',
    sync: false,
    filePath: 'post/backend/outboundTask/search/data',
    id: 18033 },
  { method: 'GET',
    url: '/backend/outboundTask/list',
    sync: true,
    filePath: 'page\\warehouseout\\taskwarehouseoutList',
    id: 11520 },
  { method: 'GET',
    url: '/backend/outboundTask/export',
    sync: false,
    filePath: 'get/backend/outboundTask/export/data',
    id: 18036 },
  { method: 'GET',
    url: '/backend/notify/msg/query',
    sync: false,
    filePath: 'get/backend/notify/msg/query/data',
    id: 18018 },
  { method: 'GET',
    url: '/backend/newGoods/save',
    sync: false,
    filePath: 'get/backend/newGoods/save/data',
    id: 17076 },
  { method: 'GET',
    url: '/backend/myContractList/list',
    sync: true,
    filePath: 'page\\supplychain\\contract\\myContractList',
    id: 11186 },
  { method: 'GET',
    url: '/backend/myContractList/getTransferingContracts',
    sync: false,
    filePath: 'get/backend/myContractList/getTransferingContracts/data',
    id: 16747 },
  { method: 'GET',
    url: '/backend/myContractList/getConfirmedContracts',
    sync: false,
    filePath: 'get/backend/myContractList/getConfirmedContracts/data',
    id: 16748 },
  { method: 'GET',
    url: '/backend/myContractList/getCompletedContracts',
    sync: false,
    filePath: 'get/backend/myContractList/getCompletedContracts/data',
    id: 16749 },
  { method: 'GET',
    url: '/backend/myContractList/batchExportContracts',
    sync: false,
    filePath: 'get/backend/myContractList/batchExportContracts/data',
    id: 16750 },
  { method: 'POST',
    url: '/backend/logis/updateLogisticsCompany',
    sync: false,
    filePath: 'post/backend/logis/updateLogisticsCompany/data',
    id: 14549 },
  { method: 'POST',
    url: '/backend/logis/updateLogisKind',
    sync: false,
    filePath: 'post/backend/logis/updateLogisKind/data',
    id: 14584 },
  { method: 'GET',
    url: '/backend/logis/queryLogisCompanyByStorage',
    sync: false,
    filePath: 'get/backend/logis/queryLogisCompanyByStorage/data',
    id: 14736 },
  { method: 'GET',
    url: '/backend/logis/queryLogisCompanies',
    sync: false,
    filePath: 'get/backend/logis/queryLogisCompanies/data',
    id: 14542 },
  { method: 'GET',
    url: '/backend/logis/queryAllLogisKinds',
    sync: false,
    filePath: 'get/backend/logis/queryAllLogisKinds/data',
    id: 14575 },
  { method: 'POST',
    url: '/backend/logis/queryAllLogisKind',
    sync: false,
    filePath: 'post/backend/logis/queryAllLogisKind/data',
    id: 14551 },
  { method: 'GET',
    url: '/backend/logis/kindIndex',
    sync: true,
    filePath: 'page\\3pl\\logisticCompanyTypeManage',
    id: 10816 },
  { method: 'POST',
    url: '/backend/logis/getSlaveWarehouses',
    sync: false,
    filePath: 'post/backend/logis/getSlaveWarehouses/data',
    id: 14552 },
  { method: 'GET',
    url: '/backend/logis/getSlaveWarehouses',
    sync: false,
    filePath: 'get/backend/logis/getSlaveWarehouses/data',
    id: 14737 },
  { method: 'POST',
    url: '/backend/logis/deleteLogisticsCompany',
    sync: false,
    filePath: 'post/backend/logis/deleteLogisticsCompany/data',
    id: 14550 },
  { method: 'POST',
    url: '/backend/logis/deleteLogisKind',
    sync: false,
    filePath: 'post/backend/logis/deleteLogisKind/data',
    id: 14585 },
  { method: 'GET',
    url: '/backend/logis/companyIndex',
    sync: true,
    filePath: 'page\\3pl\\logisticCompanyManage',
    id: 10808 },
  { method: 'POST',
    url: '/backend/logis/addLogisticsCompany',
    sync: false,
    filePath: 'post/backend/logis/addLogisticsCompany/data',
    id: 14548 },
  { method: 'POST',
    url: '/backend/logis/addLogisKind',
    sync: false,
    filePath: 'post/backend/logis/addLogisKind/data',
    id: 14583 },
  { method: 'GET',
    url: '/backend/linkto',
    sync: true,
    filePath: 'page\\iframe',
    id: 11161 },
  { method: 'POST',
    url: '/backend/invoicing/order/tallyreport/audit',
    sync: false,
    filePath: 'post/backend/invoicing/order/tallyreport/audit/data',
    id: 20268 },
  { method: 'POST',
    url: '/backend/invoicing/order/tallyreport',
    sync: false,
    filePath: 'post/backend/invoicing/order/tallyreport/data',
    id: 20267 },
  { method: 'GET',
    url: '/backend/index',
    sync: true,
    filePath: 'page\\index',
    id: 11513 },
  { method: 'POST',
    url: '/backend/homepage/tasks/update',
    sync: false,
    filePath: 'post/backend/homepage/tasks/update/data',
    id: 18021 },
  { method: 'POST',
    url: '/backend/homepage/quickentries/update',
    sync: false,
    filePath: 'post/backend/homepage/quickentries/update/data',
    id: 18008 },
  { method: 'POST',
    url: '/backend/homepage/quickentries/getquickentries',
    sync: false,
    filePath: 'post/backend/homepage/quickentries/getquickentries/data',
    id: 18103 },
  { method: 'POST',
    url: '/backend/homepage/getpendingtaskList',
    sync: false,
    filePath: 'post/backend/homepage/getpendingtaskList/data',
    id: 18104 },
  { method: 'POST',
    url: '/backend/homepage/entry/remove',
    sync: false,
    filePath: 'post/backend/homepage/entry/remove/data',
    id: 18017 },
  { method: 'DELETE',
    url: '/backend/homepage/entry/add',
    sync: false,
    filePath: 'delete/backend/homepage/entry/add/data',
    id: 18016 },
  { method: 'GET',
    url: '/backend/homepage/config/meta',
    sync: true,
    filePath: 'page\\homepage\\config\\meta',
    id: 11512 },
  { method: 'GET',
    url: '/backend/homepage/config',
    sync: true,
    filePath: 'page\\homepage\\config\\config',
    id: 11509 },
  { method: 'GET',
    url: '/backend/goodstransfer/taskSearch',
    sync: false,
    filePath: 'get/backend/goodstransfer/taskSearch/data',
    id: 15463 },
  { method: 'GET',
    url: '/backend/goodstransfer/taskListPage',
    sync: true,
    filePath: 'page\\goodstransfer\\taskList',
    id: 10986 },
  { method: 'GET',
    url: '/backend/goodstransfer/searchGoods',
    sync: false,
    filePath: 'get/backend/goodstransfer/searchGoods/data',
    id: 15222 },
  { method: 'GET',
    url: '/backend/goodstransfer/search',
    sync: false,
    filePath: 'get/backend/goodstransfer/search/data',
    id: 15136 },
  { method: 'POST',
    url: '/backend/goodstransfer/save',
    sync: false,
    filePath: 'post/backend/goodstransfer/save/data',
    id: 15140 },
  { method: 'GET',
    url: '/backend/goodstransfer/rejectAudit',
    sync: false,
    filePath: 'get/backend/goodstransfer/rejectAudit/data',
    id: 15315 },
  { method: 'GET',
    url: '/backend/goodstransfer/passAudit',
    sync: false,
    filePath: 'get/backend/goodstransfer/passAudit/data',
    id: 15314 },
  { method: 'GET',
    url: '/backend/goodstransfer/newGoodsTransfer',
    sync: true,
    filePath: 'page\\goodstransfer\\goodsTransferOrder',
    id: 10917 },
  { method: 'GET',
    url: '/backend/goodstransfer/listPage',
    sync: true,
    filePath: 'page\\goodstransfer\\goodsTransferList',
    id: 10916 },
  { method: 'POST',
    url: '/backend/goodstransfer/importGoods',
    sync: false,
    filePath: 'post/backend/goodstransfer/importGoods/data',
    id: 15224 },
  { method: 'GET',
    url: '/backend/goodstransfer/feeEnter',
    sync: false,
    filePath: 'get/backend/goodstransfer/feeEnter/data',
    id: 15319 },
  { method: 'GET',
    url: '/backend/goodstransfer/detailPage',
    sync: true,
    filePath: 'page\\goodstransfer\\goodsTransferOrder',
    id: 10917 },
  { method: 'GET',
    url: '/backend/goodstransfer/delete',
    sync: false,
    filePath: 'get/backend/goodstransfer/delete/data',
    id: 15138 },
  { method: 'GET',
    url: '/backend/goodstransfer/confirmStockOut',
    sync: false,
    filePath: 'get/backend/goodstransfer/confirmStockOut/data',
    id: 15681 },
  { method: 'GET',
    url: '/backend/goodstransfer/confirmStockIn',
    sync: false,
    filePath: 'get/backend/goodstransfer/confirmStockIn/data',
    id: 15682 },
  { method: 'POST',
    url: '/backend/goodstransfer/commit',
    sync: false,
    filePath: 'post/backend/goodstransfer/commit/data',
    id: 15141 },
  { method: 'GET',
    url: '/backend/goodstransfer/cancelAudit',
    sync: false,
    filePath: 'get/backend/goodstransfer/cancelAudit/data',
    id: 15316 },
  { method: 'POST',
    url: '/backend/goodslife/reject',
    sync: false,
    filePath: 'post/backend/goodslife/reject/data',
    id: 17120 },
  { method: 'GET',
    url: '/backend/goodslife/pending/list',
    sync: false,
    filePath: 'get/backend/goodslife/pending/list/data',
    id: 17118 },
  { method: 'GET',
    url: '/backend/goodslife/manage/list',
    sync: false,
    filePath: 'get/backend/goodslife/manage/list/data',
    id: 17096 },
  { method: 'GET',
    url: '/backend/goodslife/manage',
    sync: true,
    filePath: 'page\\goodslife\\statusMngList',
    id: 11230 },
  { method: 'GET',
    url: '/backend/goodslife/import',
    sync: false,
    filePath: 'get/backend/goodslife/import/data',
    id: 17101 },
  { method: 'GET',
    url: '/backend/goodslife/export',
    sync: false,
    filePath: 'get/backend/goodslife/export/data',
    id: 17100 },
  { method: 'POST',
    url: '/backend/goodslife/audit',
    sync: false,
    filePath: 'post/backend/goodslife/audit/data',
    id: 17119 },
  { method: 'POST',
    url: '/backend/goodslife/askforAudit',
    sync: false,
    filePath: 'post/backend/goodslife/askforAudit/data',
    id: 17099 },
  { method: 'GET',
    url: '/backend/goodlife/newgood',
    sync: false,
    filePath: 'get/backend/goodlife/newgood/data',
    id: 17098 },
  { method: 'POST',
    url: '/backend/express/removeExpressTemplate',
    sync: false,
    filePath: 'post/backend/express/removeExpressTemplate/data',
    id: 16994 },
  { method: 'POST',
    url: '/backend/express/recount',
    sync: false,
    filePath: 'post/backend/express/recount/data',
    id: 17000 },
  { method: 'POST',
    url: '/backend/express/preRemoveExpressTemplate',
    sync: false,
    filePath: 'post/backend/express/preRemoveExpressTemplate/data',
    id: 17521 },
  { method: 'GET',
    url: '/backend/express/listExpressTemplate',
    sync: false,
    filePath: 'get/backend/express/listExpressTemplate/data',
    id: 16991 },
  { method: 'GET',
    url: '/backend/express/list',
    sync: true,
    filePath: 'page\\3pl\\express\\list',
    id: 11217 },
  { method: 'GET',
    url: '/backend/express/index',
    sync: true,
    filePath: 'page\\3pl\\express\\index',
    id: 11218 },
  { method: 'GET',
    url: '/backend/express/getLogisticsCompany',
    sync: false,
    filePath: 'get/backend/express/getLogisticsCompany/data',
    id: 16995 },
  { method: 'POST',
    url: '/backend/express/getExpressList',
    sync: false,
    filePath: 'post/backend/express/getExpressList/data',
    id: 16996 },
  { method: 'POST',
    url: '/backend/express/expressAddInfo',
    sync: false,
    filePath: 'post/backend/express/expressAddInfo/data',
    id: 17196 },
  { method: 'POST',
    url: '/backend/express/editExpressBid',
    sync: false,
    filePath: 'post/backend/express/editExpressBid/data',
    id: 16998 },
  { method: 'GET',
    url: '/backend/express/edit',
    sync: true,
    filePath: 'page\\3pl\\express\\create',
    id: 11216 },
  { method: 'POST',
    url: '/backend/express/deleteExpressBid',
    sync: false,
    filePath: 'post/backend/express/deleteExpressBid/data',
    id: 17052 },
  { method: 'GET',
    url: '/backend/express/create',
    sync: true,
    filePath: 'page\\3pl\\express\\create',
    id: 11216 },
  { method: 'POST',
    url: '/backend/express/copyExpressTemplate',
    sync: false,
    filePath: 'post/backend/express/copyExpressTemplate/data',
    id: 17002 },
  { method: 'POST',
    url: '/backend/express/changeType',
    sync: false,
    filePath: 'post/backend/express/changeType/data',
    id: 17001 },
  { method: 'POST',
    url: '/backend/express/addFeeBid',
    sync: false,
    filePath: 'post/backend/express/addFeeBid/data',
    id: 16999 },
  { method: 'GET',
    url: '/backend/dw/export/auditStatistics/totalAmount',
    sync: false,
    filePath: 'get/backend/dw/export/auditStatistics/totalAmount/data',
    id: 17667 },
  { method: 'GET',
    url: '/backend/dw/export/auditStatistics/list',
    sync: false,
    filePath: 'get/backend/dw/export/auditStatistics/list/data',
    id: 17652 },
  { method: 'GET',
    url: '/backend/dw/export/auditStatistics/export',
    sync: false,
    filePath: 'get/backend/dw/export/auditStatistics/export/data',
    id: 17662 },
  { method: 'GET',
    url: '/backend/dw/export/auditStatistics',
    sync: true,
    filePath: 'page\\dw\\auditStatistics',
    id: 11461 },
  { method: 'POST',
    url: '/backend/dlcenter/upload',
    sync: false,
    filePath: 'post/backend/dlcenter/upload/data',
    id: 18950 },
  { method: 'GET',
    url: '/backend/dlcenter/list',
    sync: false,
    filePath: 'get/backend/dlcenter/list/data',
    id: 18949 },
  { method: 'GET',
    url: '/backend/dlcenter/index',
    sync: true,
    filePath: 'page\\dlcenter\\index',
    id: 11721 },
  { method: 'POST',
    url: '/backend/dlcenter/delete',
    sync: false,
    filePath: 'post/backend/dlcenter/delete/data',
    id: 18948 },
  { method: 'POST',
    url: '/backend/districtDelivery/updateDistrictScheme',
    sync: false,
    filePath: 'post/backend/districtDelivery/updateDistrictScheme/data',
    id: 14721 },
  { method: 'GET',
    url: '/backend/districtDelivery/updateDefaultLogistic',
    sync: false,
    filePath: 'get/backend/districtDelivery/updateDefaultLogistic/data',
    id: 14738 },
  { method: 'POST',
    url: '/backend/districtDelivery/saveGoodsSchemeSort',
    sync: false,
    filePath: 'post/backend/districtDelivery/saveGoodsSchemeSort/data',
    id: 14709 },
  { method: 'POST',
    url: '/backend/districtDelivery/queryOperationLog',
    sync: false,
    filePath: 'post/backend/districtDelivery/queryOperationLog/data',
    id: 14866 },
  { method: 'GET',
    url: '/backend/districtDelivery/queryGoodsdistribution',
    sync: false,
    filePath: 'get/backend/districtDelivery/queryGoodsdistribution/data',
    id: 14624 },
  { method: 'GET',
    url: '/backend/districtDelivery/queryDistrictScheme',
    sync: false,
    filePath: 'get/backend/districtDelivery/queryDistrictScheme/data',
    id: 14715 },
  { method: 'GET',
    url: '/backend/districtDelivery/queryDefaultLogistic',
    sync: false,
    filePath: 'get/backend/districtDelivery/queryDefaultLogistic/data',
    id: 14637 },
  { method: 'GET',
    url: '/backend/districtDelivery/queryDefaultLogis',
    sync: false,
    filePath: 'get/backend/districtDelivery/queryDefaultLogis/data',
    id: 14729 },
  { method: 'POST',
    url: '/backend/districtDelivery/queryAreaDetailByDistrictIds',
    sync: false,
    filePath: 'post/backend/districtDelivery/queryAreaDetailByDistrictIds/data',
    id: 14854 },
  { method: 'GET',
    url: '/backend/districtDelivery/importDistrictSchemeTemplate',
    sync: false,
    filePath: 'get/backend/districtDelivery/importDistrictSchemeTemplate/data',
    id: 14735 },
  { method: 'POST',
    url: '/backend/districtDelivery/importDistrictScheme',
    sync: false,
    filePath: 'post/backend/districtDelivery/importDistrictScheme/data',
    id: 14724 },
  { method: 'GET',
    url: '/backend/districtDelivery/getGoodsSchemeDetail',
    sync: false,
    filePath: 'get/backend/districtDelivery/getGoodsSchemeDetail/data',
    id: 14651 },
  { method: 'GET',
    url: '/backend/districtDelivery/getGoodsList',
    sync: false,
    filePath: 'get/backend/districtDelivery/getGoodsList/data',
    id: 14665 },
  { method: 'GET',
    url: '/backend/districtDelivery/getCategoryList',
    sync: false,
    filePath: 'get/backend/districtDelivery/getCategoryList/data',
    id: 14657 },
  { method: 'POST',
    url: '/backend/districtDelivery/getAreaBeginWithRegion',
    sync: false,
    filePath: 'post/backend/districtDelivery/getAreaBeginWithRegion/data',
    id: 14814 },
  { method: 'GET',
    url: '/backend/districtDelivery/getAreaBeginWithProvince',
    sync: false,
    filePath: 'get/backend/districtDelivery/getAreaBeginWithProvince/data',
    id: 14727 },
  { method: 'GET',
    url: '/backend/districtDelivery/getAreaBeginWithCountry',
    sync: false,
    filePath: 'get/backend/districtDelivery/getAreaBeginWithCountry/data',
    id: 14728 },
  { method: 'GET',
    url: '/backend/districtDelivery/exportDistrictScheme',
    sync: false,
    filePath: 'get/backend/districtDelivery/exportDistrictScheme/data',
    id: 14726 },
  { method: 'GET',
    url: '/backend/districtDelivery/downloadGoodsTable',
    sync: false,
    filePath: 'get/backend/districtDelivery/downloadGoodsTable/data',
    id: 14696 },
  { method: 'GET',
    url: '/backend/districtDelivery/distributionScheme',
    sync: true,
    filePath: 'page\\3pl\\distributionScheme',
    id: 10826 },
  { method: 'GET',
    url: '/backend/districtDelivery/deleteGoodsScheme',
    sync: false,
    filePath: 'get/backend/districtDelivery/deleteGoodsScheme/data',
    id: 14695 },
  { method: 'GET',
    url: '/backend/districtDelivery/deleteDistrictScheme',
    sync: false,
    filePath: 'get/backend/districtDelivery/deleteDistrictScheme/data',
    id: 14722 },
  { method: 'GET',
    url: '/backend/districtDelivery/addLocationImportTemplate',
    sync: false,
    filePath: 'get/backend/districtDelivery/addLocationImportTemplate/data',
    id: 14655 },
  { method: 'GET',
    url: '/backend/districtDelivery/addLocationImport',
    sync: false,
    filePath: 'get/backend/districtDelivery/addLocationImport/data',
    id: 14672 },
  { method: 'GET',
    url: '/backend/districtDelivery/addGoodsScheme',
    sync: true,
    filePath: 'page\\3pl\\addGoodsScheme',
    id: 10837 },
  { method: 'GET',
    url: '/backend/districtDelivery/addGoodsImportTemplate',
    sync: false,
    filePath: 'get/backend/districtDelivery/addGoodsImportTemplate/data',
    id: 14654 },
  { method: 'GET',
    url: '/backend/districtDelivery/addGoodsImport',
    sync: false,
    filePath: 'get/backend/districtDelivery/addGoodsImport/data',
    id: 14670 },
  { method: 'POST',
    url: '/backend/districtDelivery/addDistrictScheme',
    sync: false,
    filePath: 'post/backend/districtDelivery/addDistrictScheme/data',
    id: 14720 },
  { method: 'POST',
    url: '/backend/districtDelivery/addCategoryGoodsScheme',
    sync: false,
    filePath: 'post/backend/districtDelivery/addCategoryGoodsScheme/data',
    id: 14691 },
  { method: 'POST',
    url: '/backend/contractTask/reject',
    sync: false,
    filePath: 'post/backend/contractTask/reject/data',
    id: 16761 },
  { method: 'POST',
    url: '/backend/contractTask/pass',
    sync: false,
    filePath: 'post/backend/contractTask/pass/data',
    id: 16760 },
  { method: 'GET',
    url: '/backend/contractTask/list',
    sync: false,
    filePath: 'get/backend/contractTask/list/data',
    id: 16753 },
  { method: 'GET',
    url: '/backend/contractTask/getPendingContracts',
    sync: false,
    filePath: 'get/backend/contractTask/getPendingContracts/data',
    id: 16754 },
  { method: 'GET',
    url: '/backend/contractTask/getApprovedContracts',
    sync: false,
    filePath: 'get/backend/contractTask/getApprovedContracts/data',
    id: 16755 },
  { method: 'POST',
    url: '/backend/contractTask/complete',
    sync: false,
    filePath: 'post/backend/contractTask/complete/data',
    id: 17061 },
  { method: 'POST',
    url: '/backend/contractTask/callback',
    sync: false,
    filePath: 'post/backend/contractTask/callback/data',
    id: 17097 },
  { method: 'GET',
    url: '/backend/contractTask/batchExportContracts',
    sync: false,
    filePath: 'get/backend/contractTask/batchExportContracts/data',
    id: 16764 },
  { method: 'GET',
    url: '/backend/contractMng/task/list',
    sync: false,
    filePath: 'get/backend/contractMng/task/list/data',
    id: 16751 },
  { method: 'GET',
    url: '/backend/contractMng/task/getAllContracts',
    sync: false,
    filePath: 'get/backend/contractMng/task/getAllContracts/data',
    id: 16752 },
  { method: 'GET',
    url: '/backend/contractMng/task/batchExportContracts',
    sync: false,
    filePath: 'get/backend/contractMng/task/batchExportContracts/data',
    id: 16766 },
  { method: 'GET',
    url: '/backend/contractDetail/uploadAttachment',
    sync: false,
    filePath: 'get/backend/contractDetail/uploadAttachment/data',
    id: 17057 },
  { method: 'POST',
    url: '/backend/contractDetail/submit',
    sync: false,
    filePath: 'post/backend/contractDetail/submit/data',
    id: 16758 },
  { method: 'POST',
    url: '/backend/contractDetail/save',
    sync: false,
    filePath: 'post/backend/contractDetail/save/data',
    id: 16757 },
  { method: 'GET',
    url: '/backend/contractDetail/preview',
    sync: false,
    filePath: 'get/backend/contractDetail/preview/data',
    id: 16762 },
  { method: 'POST',
    url: '/backend/contractDetail/new',
    sync: false,
    filePath: 'post/backend/contractDetail/new/data',
    id: 16883 },
  { method: 'GET',
    url: '/backend/contractDetail/download',
    sync: false,
    filePath: 'get/backend/contractDetail/download/data',
    id: 17137 },
  { method: 'GET',
    url: '/backend/contractDetail/detailPDF',
    sync: true,
    filePath: 'page\\contractDetail\\detailPDF',
    id: 11449 },
  { method: 'POST',
    url: '/backend/contractDetail/detail',
    sync: false,
    filePath: 'post/backend/contractDetail/detail/data',
    id: 16745 },
  { method: 'GET',
    url: '/backend/contractDetail/detail',
    sync: true,
    filePath: 'page\\supplychain\\contract\\contractDetail',
    id: 11183 },
  { method: 'GET',
    url: '/backend/contractDetail/deleteAttachment',
    sync: false,
    filePath: 'get/backend/contractDetail/deleteAttachment/data',
    id: 17060 },
  { method: 'DELETE',
    url: '/backend/contractDetail/delete',
    sync: false,
    filePath: 'delete/backend/contractDetail/delete/data',
    id: 16759 },
  { method: 'GET',
    url: '/backend/contractDetail/create',
    sync: true,
    filePath: 'page\\supplychain\\contract\\contractDetail',
    id: 11183 },
  { method: 'POST',
    url: '/backend/category/brands',
    sync: false,
    filePath: 'post/backend/category/brands/data',
    id: 16228 },
  { method: 'POST',
    url: '/backend/capitalpool/search',
    sync: false,
    filePath: 'post/backend/capitalpool/search/data',
    id: 17894 },
  { method: 'POST',
    url: '/backend/capitalpool/saveCustomCategory',
    sync: false,
    filePath: 'post/backend/capitalpool/saveCustomCategory/data',
    id: 17981 },
  { method: 'GET',
    url: '/backend/capitalpool/listPage',
    sync: true,
    filePath: 'page\\capitalpool\\capitalpoollist',
    id: 11495 },
  { method: 'GET',
    url: '/backend/capitalpool/getCategoriesTree',
    sync: false,
    filePath: 'get/backend/capitalpool/getCategoriesTree/data',
    id: 17992 },
  { method: 'POST',
    url: '/backend/capitalpool/exportlist',
    sync: false,
    filePath: 'post/backend/capitalpool/exportlist/data',
    id: 17896 },
  { method: 'POST',
    url: '/backend/capitalpool/exportdetailPage',
    sync: false,
    filePath: 'post/backend/capitalpool/exportdetailPage/data',
    id: 17983 },
  { method: 'POST',
    url: '/backend/capitalpool/editCycleInventoryDay',
    sync: false,
    filePath: 'post/backend/capitalpool/editCycleInventoryDay/data',
    id: 18037 },
  { method: 'GET',
    url: '/backend/capitalpool/detailPage',
    sync: true,
    filePath: 'page\\capitalpool\\customcategorydetail',
    id: 11496 },
  { method: 'POST',
    url: '/backend/capitalpool/deleteCustomCategory',
    sync: false,
    filePath: 'post/backend/capitalpool/deleteCustomCategory/data',
    id: 18005 },
  { method: 'POST',
    url: '/backend/candidateSku/searchAuditing',
    sync: false,
    filePath: 'post/backend/candidateSku/searchAuditing/data',
    id: 20122 },
  { method: 'POST',
    url: '/backend/candidateSku/searchAudited',
    sync: false,
    filePath: 'post/backend/candidateSku/searchAudited/data',
    id: 20125 },
  { method: 'GET',
    url: '/backend/candidateSku/manage',
    sync: true,
    filePath: 'page\\report\\index',
    id: 11899 },
  { method: 'GET',
    url: '/backend/candidateSku/fetchAuditingCandidateSku',
    sync: true,
    filePath: 'page\\report\\detail',
    id: 11900 },
  { method: 'GET',
    url: '/backend/candidateSku/fetchAuditedCandidateSku',
    sync: true,
    filePath: 'page\\report\\detail',
    id: 11900 },
  { method: 'GET',
    url: '/backend/candidateSku/audit',
    sync: false,
    filePath: 'get/backend/candidateSku/audit/data',
    id: 20123 },
  { method: 'GET',
    url: '/backend/brandTask/search',
    sync: false,
    filePath: 'get/backend/brandTask/search/data',
    id: 20115 },
  { method: 'POST',
    url: '/backend/brandTask/relate',
    sync: false,
    filePath: 'post/backend/brandTask/relate/data',
    id: 20119 },
  { method: 'POST',
    url: '/backend/brandTask/process',
    sync: false,
    filePath: 'post/backend/brandTask/process/data',
    id: 20118 },
  { method: 'POST',
    url: '/backend/brandTask/msBrand',
    sync: false,
    filePath: 'post/backend/brandTask/msBrand/data',
    id: 20132 },
  { method: 'POST',
    url: '/backend/brandTask/list',
    sync: false,
    filePath: 'post/backend/brandTask/list/data',
    id: 20120 },
  { method: 'GET',
    url: '/backend/brandTask/index',
    sync: true,
    filePath: 'page\\brandTask\\index',
    id: 11898 },
  { method: 'POST',
    url: '/backend/brandTask/export',
    sync: false,
    filePath: 'post/backend/brandTask/export/data',
    id: 20116 },
  { method: 'GET',
    url: '/backend/brandTask/detail',
    sync: true,
    filePath: 'page\\brandTask\\detail',
    id: 11927 },
  { method: 'POST',
    url: '/backend/brandTask/detail',
    sync: false,
    filePath: 'post/backend/brandTask/detail/data',
    id: 20121 },
  { method: 'POST',
    url: '/backend/brandTask/checkAssociatedSkuExist',
    sync: false,
    filePath: 'post/backend/brandTask/checkAssociatedSkuExist/data',
    id: 20117 },
  { method: 'GET',
    url: '/backend/backendSkuRecord/packageDownload',
    sync: false,
    filePath: 'get/backend/backendSkuRecord/packageDownload/data',
    id: 20304 },
  { method: 'POST',
    url: '/backend/backendSkuRecord/list',
    sync: false,
    filePath: 'post/backend/backendSkuRecord/list/data',
    id: 20091 },
  { method: 'GET',
    url: '/backend/backendSkuRecord/index',
    sync: true,
    filePath: 'page\\backendSkuRecord\\index',
    id: 11896 },
  { method: 'POST',
    url: '/backend/backendSkuRecord/export',
    sync: false,
    filePath: 'post/backend/backendSkuRecord/export/data',
    id: 20092 },
  { method: 'GET',
    url: '/backend/backendSkuRecord/detail',
    sync: true,
    filePath: 'page\\backendSkuRecord\\detail',
    id: 11932 },
  { method: 'POST',
    url: '/backend/auditDetail/supplierConfirm',
    sync: false,
    filePath: 'post/backend/auditDetail/supplierConfirm/data',
    id: 16816 },
  { method: 'POST',
    url: '/backend/account/balance/update',
    sync: false,
    filePath: 'post/backend/account/balance/update/data',
    id: 16284 },
  { method: 'POST',
    url: '/backend/account/balance/list',
    sync: false,
    filePath: 'post/backend/account/balance/list/data',
    id: 16283 },
  { method: 'GET',
    url: '/backend/account/balance/init',
    sync: true,
    filePath: 'page\\accountWarning\\ini',
    id: 11121 },
  { method: 'POST',
    url: '/backend/account/balance/delete',
    sync: false,
    filePath: 'post/backend/account/balance/delete/data',
    id: 16279 },
  { method: 'POST',
    url: '/backend/account/balance/addSubscriberEmail',
    sync: false,
    filePath: 'post/backend/account/balance/addSubscriberEmail/data',
    id: 16281 },
  { method: 'POST',
    url: '/backend/account/balance/add',
    sync: false,
    filePath: 'post/backend/account/balance/add/data',
    id: 16278 },
  { method: 'POST',
    url: '/backend/HSWhiteList/update',
    sync: false,
    filePath: 'post/backend/HSWhiteList/update/data',
    id: 16229 },
  { method: 'GET',
    url: '/backend/HSWhiteList/list',
    sync: false,
    filePath: 'get/backend/HSWhiteList/list/data',
    id: 16224 },
  { method: 'GET',
    url: '/backend/HSWhiteList/index',
    sync: true,
    filePath: 'page\\supplymanage\\whitelist',
    id: 11113 },
  { method: 'POST',
    url: '/backend/HSWhiteList/import',
    sync: false,
    filePath: 'post/backend/HSWhiteList/import/data',
    id: 16225 },
  { method: 'POST',
    url: '/backend/HSWhiteList/delete',
    sync: false,
    filePath: 'post/backend/HSWhiteList/delete/data',
    id: 16226 },
  { method: 'POST',
    url: '/backend/HSWhiteList/add',
    sync: false,
    filePath: 'post/backend/HSWhiteList/add/data',
    id: 16372 },
  { method: 'GET',
    url: '/',
    sync: false,
    filePath: 'get/data',
    id: 20131 } ]