module.exports = [ { method: 'GET',
    url: '/backend/outbound/newOutboundPage',
    sync: false,
    filePath: 'get/backend/outbound/newOutboundPage/data',
    id: 18035 },
  { method: 'POST',
    url: '/storage/template/submit',
    sync: false,
    filePath: 'post/storage/template/submit/data',
    id: 16975 },
  { method: 'POST',
    url: '/storage/template/remove',
    sync: false,
    filePath: 'post/storage/template/remove/data',
    id: 16969 },
  { method: 'GET',
    url: '/storage/template/init',
    sync: true,
    filePath: 'page/4pl/expenseTemplate/list',
    id: 11213 } ]
